# Generated by Django 2.1.7 on 2020-12-06 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccademicSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=191)),
                ('accademic_year', models.CharField(max_length=191)),
                ('session', models.CharField(max_length=191)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accademicsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.AccademicSession')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_level', models.CharField(max_length=191)),
                ('lecturer_sirname', models.CharField(max_length=191)),
                ('other_name', models.CharField(max_length=191)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=191)),
                ('tel', models.CharField(max_length=191)),
                ('user_id_or_pe_nember', models.CharField(max_length=191)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('code', models.CharField(max_length=191)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='staffprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.StaffProfile'),
        ),
        migrations.AddField(
            model_name='report',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Unit'),
        ),
    ]
